package br.com.jetpack.compose.utils

internal object ComponentsDestinations {
    const val HOME_ROUTE = "HOME_ROUTE"
    const val COLUMN_CONTAINER_ROUTE = "COLUMN_CONTAINER_ROUTE"
    const val ROW_CONTAINER_ROUTE = "ROW_CONTAINER_ROUTE"
    const val LAZY_LIST_VERTICAL_CONTAINER_ROUTE = "LAZY_LIST_VERTICAL_CONTAINER_ROUTE"
    const val LAZY_LIST_HORIZONTAL_CONTAINER_ROUTE = "LAZY_LIST_HORIZONTAL_CONTAINER_ROUTE"
    const val LAZY_GRID_CONTAINER_ROUTE = "LAZY_GRID_CONTAINER_ROUTE"
}